name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:  # å…è®¸æ‰‹åŠ¨è§¦å‘

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # ğŸš€ Step 1: æ£€å‡ºä»£ç 
      - name: Checkout repository
        uses: actions/checkout@v3

      # setup qemu
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64

      # setup buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ğŸ‹ Step 2: ç™»å½• Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ğŸ“¦ Step 3: æ„å»º Docker é•œåƒ
      - name: Build Docker Image
        run: |
          docker buildx build --platform linux/arm64 -t my-docker-image:latest --load .

      # æ£€æŸ¥é•œåƒæ˜¯å¦å­˜åœ¨
      - name: Check built images
        run: |
          docker images

      # ğŸ”„ Step 4: æ‰“ Tag
      - name: Tag Docker Image
        run: |
          docker tag my-docker-image:latest ${{ secrets.DOCKER_USERNAME }}/my-docker-image:latest

      # ğŸš€ Step 5: æ¨é€åˆ° Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-docker-image:latest
